### ISSUE TITLE
TcpSocketClient.Dispose(): NullReferenceException

### ISSUE THREAD

**Issue by falahati** [1iveowl/SocketLite.PCL#1]
https://github.com/1iveowl/SocketLite.PCL/blob/master/src/main/Foundation/SocketLite.NET/Services/TcpSocketClient.cs#L211

This lines throw a NullReferenceException while socket is disconnected. Please consider checking for null before calling dispose.

Thanks

**Comment by 1iveowl** [comment]
Thanks for raising this. 

I've not come across this myself, however it's an easy fix and you find it in 2.0.6. It will also be added to version 3.x and beyond. 

Did this fix it?

**Comment by falahati** [comment]
Yes it did, thanks
It is now possible to use `using` statement on this object which makes the code little shorter.
