### ISSUE TITLE
not compatible with profile 259

### ISSUE THREAD

**Issue by ElD4n1** [1iveowl/SocketLite.PCL#4]
I am working with Xamarin Forms and want to build an application mainly for Android and iOS, my current setup is using profile 259 which seems to not work with SocketLite.PCL.
Is it possible to make it compatible or can you explain me how to switch to a compatible profile?

I am getting an error when installing the package with nuget which says that my project is related to ".NETPortable,Version=v4.5,Profile=Profile259", but the package contains no assembly references that are compatible with that framework.

**Comment by ElD4n1** [comment]
Now I disabled WinPhone support which changed the project to profile 7, but it doesn't install there either with the same error message (except there is Profile7 instead of Profile259 now).

**Comment by 1iveowl** [comment]
Neither will work with the latest version of SocketLite.PCL. 

However for Profile7 (and Profile111) you can use version 2.0.20 of SocketLite. I will not be maintaining that release going forward. But the differences between 3.6.2 and 2.0.20 are currently not that great. 

As of version 3.0.0+ I moved to anything compatible with .NET 4.5.1+, iOS, UWP, Android and .NET Standard 1.6+. This excludes Profile256, Profile7 and Profile111. 

Do you really need to support Windows 8.x and Windows Phone 8x and .NET older than 4.5.1?

**Comment by ElD4n1** [comment]
Thanks for your reply, I already figured out that the Profile111 version also works with Profile7 after trying around myself a bit longer (shame on me), so I was working with that since yesterday.

But no, actually I just want to support the recent versions of all OS'es, so if I change the .NET version to 4.5.1 then the newest version will work for me?

**Comment by 1iveowl** [comment]
Yes, it should work with .NET 4.5.1+. And you can use the newest version 3.6.2 too. 

If it doesn't work let me know ;-)
